### ISSUE TITLE
nine-point stencil in README

### ISSUE THREAD

**Issue by tkphd** [usnistgov/hiperc#50]
Per @amjokisaari:
- [x] Create table showing 5-point and 9-point stencil
- [x] Explain how the sum of coefficients sums to zero, if ```dx=dy=h```

**Comment by amjokisaari** [comment]
Might want to clarify that there's more than one nine-point stencil form and you're doing 1st/2nd neighbors.

**Comment by tkphd** [comment]
OK. I'll clarify that in the README, but also mention that a user could implement the 1st/3rd-neighbor version with minor modifications in the docstrings.
