### ISSUE TITLE
variable names

### ISSUE THREAD

**Issue by tkphd** [usnistgov/hiperc#51]
Per @amjokisaari:
- [x] Change from math labels (```A```, ```B```, ```C```) to matsci labels (```oldGrid```, ```newGrid```, ```convGrid```)
- [x] Eliminate ```dataX``` arrays

**Comment by amjokisaari** [comment]
oldGrid, newGrid, convGrid are still confusing to a new reader, though.  I'm used to thinking of the mesh as separate from the data (sort of) as in FEM, so it looks like you're manipulating the mesh, not the concentration field with those names.

**Comment by tkphd** [comment]
```conc_old```, ```conc_new```, ```conc_src```?

**Comment by amjokisaari** [comment]
like that, but what is "src"?

**Comment by tkphd** [comment]
"src" is "source," representing the Laplacian term which is a source or sink of mass in the point. I'll obviously include that in the docstrings.

**Comment by amjokisaari** [comment]
what about lap_conc ?

**Comment by tkphd** [comment]
That would work.
