### ISSUE TITLE
dynamic documentation

### ISSUE THREAD

**Issue by tkphd** [usnistgov/hiperc#52]
Per @amjokisaari:
- [x] Apply lessons from the [Art of README](https://github.com/noffle/art-of-readme)
- [x] Apply lessons from Code Complete
- [x] Include terms of use in implementation files
- [x] Annotate function implementations with brief and extended statements of purpose, inputs, outputs, etc. (Doxygen-compatible syntax)
- [x] Document flow of data, explain how ```c``` gets computed
- [x] Use [Doxygen](http://www.stack.nl/~dimitri/doxygen/) to convert comments to documentation
- [x] Bridge Doxygen to [Sphinx](http://www.sphinx-doc.org/en/stable/) using [Breathe](https://breathe.readthedocs.io/en/latest/)

**Comment by amjokisaari** [comment]
YES PLEASE use Doxygen.  That would make navigating the code a lot easier.

**Comment by tkphd** [comment]
Closed by 7a139a2.
