### ISSUE TITLE
Warnings when compiling cpu version

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/hiperc#56]
make[1]: Entering directory '/home/amj/projects/phasefield-accelerator-benchmarks/cpu/tbb'
g++ -O2 -Wall -pedantic -std=c++11 -I../ -c boundaries.cpp
In file included from /opt/moose/tbb/include/tbb/tbb.h:68:0,
                 from boundaries.cpp:10:
/opt/moose/tbb/include/tbb/pipeline.h:328:74: warning: ‘template<class _Tp> struct std::has_trivial_copy_constructor’ is deprecated [-Wdeprecated-declarations]
 template<typename T> struct tbb_trivially_copyable { enum { value = std::has_trivial_copy_constructor<T>::value }; };
                                                                          ^
In file included from /opt/moose/gcc-5.3.0/include/c++/5.3.0/bits/move.h:57:0,
                 from /opt/moose/gcc-5.3.0/include/c++/5.3.0/bits/stl_pair.h:59,
                 from /opt/moose/gcc-5.3.0/include/c++/5.3.0/bits/stl_algobase.h:64,
                 from /opt/moose/gcc-5.3.0/include/c++/5.3.0/memory:62,
                 from /opt/moose/tbb/include/tbb/tbb_stddef.h:421,
                 from /opt/moose/tbb/include/tbb/aligned_space.h:24,
                 from /opt/moose/tbb/include/tbb/tbb.h:35,
                 from boundaries.cpp:10:
/opt/moose/gcc-5.3.0/include/c++/5.3.0/type_traits:1389:12: note: declared here
     struct has_trivial_copy_constructor
            ^
g++ -O2 -Wall -pedantic -std=c++11 -I../ -c discretization.cpp
In file included from /opt/moose/tbb/include/tbb/tbb.h:68:0,
                 from discretization.cpp:10:
/opt/moose/tbb/include/tbb/pipeline.h:328:74: warning: ‘template<class _Tp> struct std::has_trivial_copy_constructor’ is deprecated [-Wdeprecated-declarations]
 template<typename T> struct tbb_trivially_copyable { enum { value = std::has_trivial_copy_constructor<T>::value }; };
                                                                          ^
In file included from /opt/moose/gcc-5.3.0/include/c++/5.3.0/bits/move.h:57:0,
                 from /opt/moose/gcc-5.3.0/include/c++/5.3.0/bits/stl_pair.h:59,
                 from /opt/moose/gcc-5.3.0/include/c++/5.3.0/bits/stl_algobase.h:64,
                 from /opt/moose/gcc-5.3.0/include/c++/5.3.0/memory:62,
                 from /opt/moose/tbb/include/tbb/tbb_stddef.h:421,
                 from /opt/moose/tbb/include/tbb/aligned_space.h:24,
                 from /opt/moose/tbb/include/tbb/tbb.h:35,
                 from discretization.cpp:10:
/opt/moose/gcc-5.3.0/include/c++/5.3.0/type_traits:1389:12: note: declared here
     struct has_trivial_copy_constructor
            ^
g++ -O2 -Wall -pedantic -std=c++11 -I../ -c ../mesh.c
g++ -O2 -Wall -pedantic -std=c++11 -I../ -c ../output.c
g++ -O2 -Wall -pedantic -std=c++11 -I../ -c ../timer.c
g++ -O2 -Wall -pedantic -std=c++11 -I../ boundaries.o discretization.o mesh.o output.o timer.o ../main.c -o diffusion -lm -lpng -ltbb
make[1]: Leaving directory '/home/amj/projects/phasefield-accelerator-benchmarks/cpu/tbb'

**Comment by tkphd** [comment]
This appears to be a local configuration issue: the TBB header is provided by MOOSE, not your OS or another first-party source. I could only suppress the warning, but would rather not specify ```-Wno-deprecated-declarations```.

**Comment by amjokisaari** [comment]
...ahh I have literally no experience with TBB, so it's totally your
call... I'm just reporting the warnings in case they're something to be
concerned about.

**Comment by tkphd** [comment]
Appreciated, thanks!
