### ISSUE TITLE
add console output during execution

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/hiperc#57]
Performing 'make run' gives me some make command info, but then it seems like the code is just hanging (it's not, but my data is being written out ...somewhere... I believe to the subdirectories).  It would be nice to:

1) get additional console output during execution so I know how far along the run is and

2) the readme in the subdirectory should tell the reader where their output is going.

**Comment by tkphd** [comment]
- [ ] steal print_progress from MMSP
- [ ] state what files get written, and where, if ```make run``` is called in both ```cpu/README.md``` and ```gpu/README.md```
- [ ] mention ways to monitor whether CPU or GPU code is running, after #45
