### ISSUE TITLE
Initial conditions / png color scheme are scary

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/hiperc#59]
It looks like the initial condition is two high-concentration lines on the edge of the computational domain, and concentration diffuses toward the center (see attached).  This IC combined with the black-and-white color scheme made the first output image look like the code had errored.  Perhaps choose a different color scheme (viridis?) and maybe consider a different initial condition.  Will it serve your purposes to put a blob of mass in the center of the domain and let it diffuse outward?
![dat_ic](https://user-images.githubusercontent.com/6676372/29472455-88eec8f2-8419-11e7-963a-f99b56528b99.png)

**Comment by tkphd** [comment]
- Black-and-white is the One True Color Scheme for single-variable output. It's painful to extract quantitative values from Viridis.
- A circular blob would work, but seems too simplistic. This half-wall fixed-value BC has been useful for testing corner cases (pun intended!) with tiled array access.
- I can definitely do a better job explaining why I made these choices and what the user should expect from the code.

**Comment by amjokisaari** [comment]
What kind of quantitative data are you expecting people to extract from the image?  Can they not do it with the csv instead?

edit: the IC makes sense, I figured it was something like that.  Also, yes, the "what to expect" thing would definitely be nice... kind of like various people's complaints about the newest benchmark III problems.

**Comment by amjokisaari** [comment]
1/4 circle on the lower-left corner of the computational domain?  ...this would allow examination of diffusion along non-axis/grid directions.

**Comment by tkphd** [comment]
- I'm not sure what kind of data people would want to extract. The point is that they could, given grayscale data.
- Since the CSV is plaintext, it uses a bit of disk space when the domain size increases. I only intend to write the final condition. Intervening checkpoints are images (compressed), only.
- A quarter-circle in one corner, or a blob that disappears, won't stress the hardware enough. It has to be an "interesting" solution.

**Comment by amjokisaari** [comment]
ok, chalk my thoughts up to more "what to expect / justification" type doco i guess!

**Comment by tkphd** [comment]
OK. Thanks for questioning the initial conditions! I clearly have some 'splaining to do.
