### ISSUE TITLE
gpu Makefile directory for OpenACC is wrong

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/hiperc#61]
The makefile has acc, but the actual directory is openacc.  No compiling here :(

[amj][~/projects/phasefield-accelerator-benchmarks/gpu]> make
make -C acc
make[1]: *** acc: No such file or directory.  Stop.
Makefile:7: recipe for target 'acc/diffusion' failed
make: *** [acc/diffusion] Error 2

**Comment by tkphd** [comment]
Gah, I have this fixed in a branch at home. Will merge today.
