### ISSUE TITLE
CUDA code fails to compile

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/hiperc#63]
[amj][~/projects/phasefield-accelerator-benchmarks/gpu]> make cuda/diffusion
make -C cuda
make[1]: Entering directory '/home/amj/projects/phasefield-accelerator-benchmarks/gpu/cuda'
nvcc -Wno-deprecated-gpu-targets -std=c++11 -gencode arch=compute_35,code=sm_35 --compiler-options="-O2 -Wall -I.. -fopenmp" -dc boundaries.c
nvcc -Wno-deprecated-gpu-targets -std=c++11 -gencode arch=compute_35,code=sm_35 --compiler-options="-O2 -Wall -I.. -fopenmp" -dc discretization.cu
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
Makefile:20: recipe for target 'discretization.o' failed
make[1]: *** [discretization.o] Error 1
make[1]: Leaving directory '/home/amj/projects/phasefield-accelerator-benchmarks/gpu/cuda'
Makefile:10: recipe for target 'cuda/diffusion' failed
make: *** [cuda/diffusion] Error 2

**Comment by tkphd** [comment]
Weird! ```memcpy``` should definitely exist.
Can you try modifying the NVCCFLAGS variable in ```gpu/cude/Makefile``` to include ```-D_FORCE_INLINES```, e.g.
```NVCXXFLAGS = -Wno-deprecated-gpu-targets -std=c++11 -D_FORCE_INLINES -gencode arch=compute_35,code=sm_35 \```

**Comment by amjokisaari** [comment]
yep, that compiled.

**Comment by tkphd** [comment]
OK... very strange, but it's a fix.
