### ISSUE TITLE
consider adding nvidia-cuda-toolkit to readme

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/hiperc#64]
The readme for the gpu directory gives suggested instructions for installing CUDA libraries with apt, but nvidia-cuda-dev isn't sufficient (doesn't install nvcc, need to install nvidia-cuda-toolkit).  (Ubuntu 16.04)

**Comment by tkphd** [comment]
OK. It might be better to link to the [Nvidia CUDA Toolkit](http://docs.nvidia.com/cuda/#axzz4q8bSCXWk), since the packaged version is several versions behind. I have not actually installed CUDA myself.

**Comment by amjokisaari** [comment]
yeah, your readme links to it too, but I figure if you put the apt command down, it should be complete...?  I know you run into versioning issues, etc etc etc.  Just a thought.

**Comment by tkphd** [comment]
Yes yes, thank you for testing the directions as-written. You're a solid trailblazer!
